name: the_mall
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_pro: ^0.0.13
  url_launcher: ^5.7.8

  cupertino_icons: ^1.0.0
  flutter_svg: ^0.17.4
  font_awesome_flutter: ^8.5.0
  firebase_auth: ^0.16.0
  cloud_firestore: ^0.13.5
  provider: ^4.1.3
  image_picker: ^0.6.7+2
  firebase_storage: ^3.1.6
  path: ^1.7.0
  uuid: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - Images/homepage.png
    - Images/food.png
    - Images/shop.png
    - Images/event.png
    - Images/mcdonalds.png


